realapp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from django.views.generic import UpdateView

app_name = 'realapp'
urlpatterns = [
    path('reg', views.RegisterUserView.as_view(), name="reg"),
    path('', views.HomeUserView.as_view(), name='home'),
    path('login', views.LoginUserView.as_view(), name="login"),
    path('adposting', views.AdPostingView.as_view(), name="adposting"),
    path('details/<int:pk>/', views.DetailUserView.as_view(), name="details"),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('edit/<int:pk>/', views.EditAdd.as_view(), name="edit"),
    path('delete/<int:pk>/', views.DeleteAdd.as_view(), name="delete"),
    path('myads/',views.MyAds.as_view(), name="myads"),
    path('registration/<str:key>', views.RegistrationSuccess.as_view(), name='product_success'),

    # path('details/',views.DetailUserView.as_view(),name='details'),

    # path('details/(?P<pk>\d+)/$/',views.DetailUserView.as_view(),name="details"),


]

realestatesite/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [


	# path('realapp/', include('realapp.urls'),name='realapp'),

    path('', include('realapp.urls'),name='realapp'),

    path('logout/',auth_views.LogoutView.as_view(next_page=''),name='logout'),

    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realapp/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser,BaseUserManager)

from django.contrib.auth.models import PermissionsMixin
from django.core.validators import RegexValidator

from django.contrib.auth.models import User
# Create your models here.


class MyUserManager(BaseUserManager):
    def create_user(self,email,password=None, mobile_no=None,name=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            mobile_no=mobile_no,
            name=name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password,name,mobile_no):
        user=self.create_user(
        email,
        password=password,name=name,mobile_no=mobile_no
    )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser=True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, unique=True)
    # mobile_no = models.IntegerField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Invalid Mobile Number !!!")
    mobile_no = models.CharField(validators=[phone_regex], max_length=10, blank=True)

    is_staff = models.BooleanField(('staff status'), default=False,)
    is_superuser = models.BooleanField(('staff status'),default=False)

    objects = MyUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'mobile_no']

class Item(models.Model):
    ITEM_TYPE = (
        ('V', 'Villa'),
        ('P', 'Plot'),
        ('F', 'Flat'),
    )
    CITY = (
        ('KOCHI','kochi'),
        ('TRIVANDRUM','trivandrum'),
        ('KOTTAYAM','kottayam'),
        ('THRISSUR','thrissur'),
        ('KOZHIKODE','kozhikode'),

    )
    item_title = models.CharField(max_length=50)
    item_description = models.CharField(max_length=90)
    item_type = models.CharField(max_length=1, choices=ITEM_TYPE)
    item_images = models.ImageField(upload_to='realapp/images')
    creator_name = models.ForeignKey(UserProfile, on_delete=models.CASCADE, )
    # contact_phone_no = models.IntegerField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Invalid Mobile Number !!!")
    contact_phone_no = models.CharField(validators=[phone_regex], max_length=10, blank=True)
    city = models.CharField(max_length=20, choices=CITY)
    price = models.IntegerField(default=1)

# for viewing data rather than objects in admin
    def __str__(self):
        return self.item_title


class Registration(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    key = models.CharField(max_length=100)

realapp/forms.py
from  django import forms
from django.contrib.auth.models import User
from .models import *


class RegisterUserForm(forms.ModelForm):
    name=forms.CharField(max_length=10)
    email=forms.EmailField(max_length=50)
    mobile_no = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {'class': 'form-control'}


    class Meta:
            model = UserProfile
            fields =['name', 'email', 'mobile_no','password']


class LoginUserForm(forms.Form):
        email = forms.EmailField(max_length=50)
        password = forms.CharField(widget=forms.PasswordInput)
        def __init__(self, *args, **kwargs):
            super(LoginUserForm, self).__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs = {'class': 'form-control'}

class AdPostingForm(forms.ModelForm):
    item_images=forms.ImageField()

    def __init__(self, *args, **kwargs):
        super(AdPostingForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {'class': 'form-control'}

    class Meta:
        model = Item
        # fields = '__all__'
        exclude = ('creator_name',)

realapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from django.contrib import messages
from django.views.generic import *
from .forms import *
from .models import *
from django.http import *
from django.contrib.auth import *
from django.contrib.auth import get_user_model
from django.views import generic
from django.views.generic.edit import UpdateView
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import *
from django.template.loader import render_to_string

from django.core.mail import send_mail
from django.core.signing import Signer

from django.contrib.auth.hashers import make_password

# Create your views here.
class RegisterUserView(FormView):

    template_name = "realapp/register.html"
    form_class = RegisterUserForm
    # success_url = '/login/'
    success_url = reverse_lazy('realapp:login')

    def form_valid(self, form):
            #obj = form.save()
            # obj.set_password(password)
            # get_user_model().objects.create_user(form.cleaned_data.get('email'),
            #                                       form.cleaned_data.get('password'),
            #                                       form.cleaned_data.get('mobile_no'),
            #                                       form.cleaned_data.get('name')
            #                                       )

            obj = form.save(commit=False)
            obj.password = make_password(obj.password)
            obj.is_active = False
            form.save()
            signer = Signer()
            signed_value = signer.sign(obj.email)
            key = ''.join(signed_value.split(':')[1:])
            reg_obj = Registration.objects.create(user=obj, key=key)
            msg_html = render_to_string('realapp/email-act.html', {'key': key})

            send_mail("123", "123", 'anjitha.test@gmail.com', [obj.email], html_message=msg_html, fail_silently=False)

            # return render(self.request, "realapp/home.html")
            return super().form_valid(form)


class LoginUserView(FormView):
    template_name = "realapp/login.html"
    form_class = LoginUserForm
    # success_url = '/home'
    # success_url = reverse_lazy('/home')

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        # try:
        print(email, password, "dddddddddddddd")
        user = authenticate(request, email=email, password=password)
        print("auth", str(authenticate(email=email, password=password)))

        if user is not None:
            login(request, user)

            return HttpResponseRedirect("/")

        else:
            return HttpResponse("wrong input")

class LogoutView(FormView):
    def get(self, request, *args, **kwargs):
        print (self.request.user.email)
        logout(request)
        return HttpResponseRedirect('/')


class AdPostingView(LoginRequiredMixin,FormView):

    # pass
    template_name = "realapp/adposting.html"
    form_class = AdPostingForm
    # success_url = '/home/'
    success_url = reverse_lazy('realapp:home')

    def form_valid(self, form):
        form.instance.creator_name=self.request.user
        form.save()
        return super(AdPostingView, self).form_valid(form)


class MyAds(generic.ListView):
    template_name = "realapp/myads.html"
    model = Item

    # def get_context_data(self, **kwargs):
    #     context = super(HomeUserView, self).get_context_data(**kwargs)
    #     print(context)
    #     return context
    def get_queryset(self):
        return Item.objects.filter(creator_name=self.request.user)


class HomeUserView(generic.ListView):
    template_name = "realapp/home.html"
    model = Item

    def get_context_data(self, **kwargs):
        context = super(HomeUserView, self).get_context_data(**kwargs)
        print(context)
        return context


class DetailUserView(generic.DetailView):
    model = Item
    template_name = 'realapp/detail.html'
    context_object_name = 'estate'

    # def get_context_data(self, *kwargs):
    #     context = super(DetailUserView, self).get_context_data(**kwargs)
    #     pidd = self.kwargs['pid']
    #     q_obj = Item.objects.get(id=pidd)
    #     context['estate'] = q_obj
    #
    #     return context


class EditAdd(UpdateView):
    model = Item
    # form_class = AdPostingForm
    # fields = '__all__'
    fields = ['item_title','item_description','item_images','city','price']
    # exclude = ('creator_name_id',)
    template_name= 'realapp/detail_edit.html'
    success_url = '/'


class DeleteAdd(DeleteView):
    model = Item
    success_url = reverse_lazy('realapp:home')


class RegistrationSuccess(TemplateView):
    template_name = 'realapp/registration-success.html'

    def get(self, request, args, *kwargs):
        key = self.kwargs.get("key")
        try:
            reg_obj = Registration.objects.get(key=key)
            reg_obj.user.is_active = True
            reg_obj.save()
            context = {'user': reg_obj, 'status': True}
            return self.render_to_response(context)
        except Registration.DoesNotExist:
            return self.render_to_response({'status': False})

    # def get_object(self, queryset=None):
    #     queryset = Item.objects.all()[:1].get()
    #     return queryset
    # queryset = Item.objects.all()


    # def get_queryset(self):
    #     self.queryset = Item.objects.all()
    #     # return queryset

    # def get_object(self):
    #     return self.request.


# class PostDeleteView(DeleteView):
#     model = Item
#     success_url = reverse_lazy('realapp:home')
#
#     def get_queryset(self):
#         owner = self.request.user
#         return self.model.objects.filter(owner=owner)

realapp/templates/realapp/adposting.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="row">
                <div class="col-sm-4"></div><div class="col-sm-4">

    <h3>please enter creator name as {{ user.email }}</h3>
    <h1>POST YOUR AD</h1>

    <form action =" " method="post" enctype="multipart/form-data">{% csrf_token %}

            {{ form.as_p }}
            <input type="submit" value="SUBMIT AD" />
    </form>
    </div>
    </div>

{% endblock %}

realapp/templates/realapp/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'realapp/css/realapp.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <!--<title> | {% block title %}{% endblock %}</title>-->



        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>


  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'realapp:home' %}">Real Estate</a>
    </div>
    <ul class="nav navbar-nav">
      <!--<li class="active"><a href="#">Home</a></li>-->

      <li><a href="{% url 'realapp:adposting' %}">POST ADD</a></li>
      {% if request.user.is_authenticated%}
        <li><a href="{%url 'realapp:logout'%}">LOG OUT</a></li>
        <li><a href="{%url 'realapp:myads'%}">MY ADS</a></li>


      {% endif %}
      <!--<li><a href="#">Page 3</a></li>-->
    </ul>
  </div>
</nav>


<!--<a href="{% url 'realapp:adposting' %}">POST AD</a>-->

  {% block content %}
  {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

realapp/templates/realapp/detail.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}





  <h1>{{estate.item_title}} </h1> <hr><br>


<div class="container">

    <div class="row">
        <div class="col-sm-4">    <img width=350px height=500px src="{{estate.item_images.url}}"/> </div>
              <div class="col-sm-8">
                <div class="panel-group">

                    <div class="panel panel-primary">
                        <div class="panel-heading">  {{estate.item_title}}</div>
                        <div class="panel-body">DESCRIPTION:  {{estate.item_description}}</div>
                        <div class="panel-body">LOCATION:   {{estate.city}} </div>
                        <div class="panel-body">PRICE:  {{estate.price}} </div>
                        <!--<div class="panel-body">   {{estate.price}}  </div>-->
                        <div class="panel-body">CONTACT PHONE NUMBER:   {{estate.contact_phone_no}}  </div>
                    </div>
                </div>
              </div>
    </div>
</div>



{% endblock %}

realapp/templates/realapp/detail_edit.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}
<form action =" " method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="UPDATE" />
    </form>
{% endblock %}

realapp/templates/realapp/email-act.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load i18n %}
{% blocktrans %}Welcome to Event and thank you for registering!{% endblocktrans %}
{% blocktrans %}Please click or copy the link below to activate your account:{% endblocktrans %}
http://127.0.0.1:8000/user/registration/{{ key }}
{% blocktrans %}If you didn't request this email or have no idea as to why you received it, please ignore it.  This activation link will valid for {{ expiration_days }} days.{% endblocktrans %}





</body>
</html>

realapp/templates/realapp/home.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}


        <h1>home</h1>
        <h3>hi {{request.user.name}} ,</h3>


        <br/>



            <!--{% if object_list %}-->
<div class="row">
                {% for item in object_list %}

                     <div class="col-md-4">

                            <div class="card"  style="background-color:white">

                                    <a href="{% url 'realapp:details' item.id %}" >{{ item.item_title }}</a>
                                 <img class="card-img-top" width=200px height=200px src="{{item.item_images.url}}"/>

                                 <div class="card-body">
                                            {{item.city}}

                                            Rs {{item.price}} /-

                                    </div>
                             </div>
                     </div>


                    {%endfor%}
</div>
            <!--{%else%}-->
                <!--<p>NO item</p>-->
            <!--{%endif%}-->
        {%endblock%}

realapp/templates/realapp/item_confirm_delete.html
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete your ad "{{ object.name }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

realapp/templates/realapp/login.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}


        <center>

         <h1>LOGIN</h1></center>
            <div class="row">
                <div class="col-sm-4"></div><div class="col-sm-4">
            <form action =" " method="post">{% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="LOGIN" />

            </form>
            <a href="{%url 'realapp:reg'%}" class="btn btn-primary t">REGISTER</a>

            </div>
            </div>

{% endblock %}

realapp/templates/realapp/myads.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}


        <h1>home</h1>
        <h3>hi {{request.user.name}} , your ads</h3>


        <br/>
<div class="row">

                    {% for item in object_list %}

                        <div class="col-md-4">

                            <div class="card"  style="background-color:white">

                                    {{ item.item_title }}
                                 <img class="card-img-top" width=200px height=200px src="{{item.item_images.url}}"/>

                                 <div class="card-body">
                                            {{item.city}}

                                            Rs {{item.price}} /-

                                     <a class="btn btn-primary" href="{%url 'realapp:edit' item.id %}">edit add</a>

                                     <a class="btn btn-primary" href="{%url 'realapp:delete' item.id %}">delete add</a>



                                 </div>
                             </div>
                        </div>
                    {% endfor %}
</div>
{%endblock%}

realapp/templates/realapp/register.html
{% extends 'realapp/base.html' %}
{% load staticfiles %}

{% block content %}

        <center><h1 >REGISTRATION</h1></center>

        <div class="row">
                <div class="col-sm-4"></div><div class="col-sm-4">

        <form action =" " method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="REGISTER" />
        </form>
        </div>
        </div>

{% endblock %}

realapp/templates/realapp/registration-sucess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load i18n %}
{% blocktrans %}Welcome to RealEstate.com and thank you for registering!{% endblocktrans %}
{% blocktrans %}Please click or copy the link below to activate your account:{% endblocktrans %}
http://127.0.0.1:8003/shopping_app/registration/{{ key }}
{% blocktrans %}If you didn't request this email or have no idea as to why you received it, please ignore it.  This activation link will valid for {{ expiration_days }} days.{% endblocktrans %}





</body>
</html>